---
name: CI
on:
  - push
  - create
  - pull_request
jobs:
  deployment1:
    runs-on: ubuntu-latest
    environment: 
      name: prod-west
    steps:
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  deployment2:
    runs-on: ubuntu-latest
    environment: 
      name: trunk
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
  deployment3:
    runs-on: ubuntu-latest
    environment: 
      name: model-east
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
